spring:
  datasource:
    url: jdbc:postgresql://localhost:6101/chat_service
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
jwt:
  secret: OLUV5b2mFXpasEyjUnijlG7B2wWt+cvkM/LnP7EZuX/OqUYDm9ZVlpSHWco8qk5oJ4FQQa5w0ghtzno5RpyB3A==
app:
  public_routes: /api/users/new,/api/auth/login,/actuator/**,/swagger-ui/**,/swagger-resources/**,/v3/api-docs/**,/swagger-ui.html,/webjars/**
